[package]
name = "check_urls"
version = "0.1.0"
authors = ["William Droz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob="0.3.0"
regex = "1"
futures = "0.3"
reqwest = "0.11.3"